services:
  - type: web
    name: floricultura-web
    env: docker
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: SENDGRID_API_KEY
        fromEnv: SENDGRID_API_KEY
